name: parcels
channels:
  - conda-forge
dependencies:
  - python=3.11
  - parcels
  - numpy
  - pandas
  - pyarrow
  - xarray
  - netcdf4
  - zarr
  - pyyaml
  - scipy
  - matplotlib
  - cartopy
  - networkx
  - pyproj
  - shapely
  - pip
  - pytest
