[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "kinematicparcels"
version = "0.1.0"
description = "Framework for YAML-driven OceanParcels Lagrangian experiments"
authors = [
    {name = "Jacopo Busatto"}
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "parcels",
    "numpy",
    "xarray",
    "netcdf4",
    "zarr",
    "pyyaml",
    "scipy",
    "matplotlib",
    "cartopy",
    "tqdm",
    "imageio>=2.34"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]


[project.scripts]
run-parcels-experiment = "kinematicparcels.runner.run_experiment:main"
run-parcels-postprocessing = "kinematicparcels.postprocessing.runner.cli:main"
convert-argo-to-zarr = "kinematicparcels.tools.argo_to_zarr:main"
convert-drifter-to-zarr = "kinematicparcels.tools.drifter_to_zarr:main"
convert-drf-to-zarr = "kinematicparcels.tools.drf_to_zarr:main"
couple-trajectories = "kinematicparcels.tools.couple_trajectories:main"
